name: CI

on:
  push:
    paths:
      - '2D Test/Assets/**'
      - '2D Test/Packages/**'
      - '2D Test/ProjectSettings/**'

jobs:
  buildForLinux:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: game-ci/unity-builder@v2
        env:
              UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
              UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
              UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: x86
          projectPath: 2D Test
          unityVersion: 2022.3.24f1
          buildName: 2DTestCi
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: WindowsBuild
          path: build/Windows
